<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'f998f68d1b6ecde1a13d8c1596f0a2f4',
  'WA_TOKEN' => '253619751981aldomire',
  'ANET_TOKEN' => '2536anet!1975-event',
  'SHOP_TOKEN' => 'shop2536core!1975s-b',
  'DATABASE_URL' => 'mysql://autoparn_dbmain:auto2536parnet1975@127.0.0.1:3306/autoparn_autoparnet2536?serverVersion=mariadb-10.5.15',
  'LOCK_DSN' => 'flock',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '9e3dd401988c4e5c597d04658f6e372b',
  'CORS_ALLOW_ORIGIN' => '^http?://(www.autoparnet.com|autoparnet.com|localhost|127\\.0\\.0\\.1|192\\.168\\.1\\.??)(:[0-9]+)?$',
);
