parameters:
    phtml      : '%kernel.project_dir%/public_html'
    scm        : '%phtml%/scm/'
    ftos       : '%phtml%/ftos/'


    appData    : '%phtml%/rfy/data/'
    sse        : '%phtml%/sse/'
    fbSended   : '%phtml%/fb_sended/'
    fbFails    : '%phtml%/fb_fails/'
    sincDev    : '%phtml%/sinc_dev/'
    prodPubs   : '%phtml%/prod_pubs/'
    prodSols   : '%phtml%/prod_sols/'
    prodTrack  : '%phtml%/prod_track/'
    trackeds   : '%phtml%/trackeds/'
    tracking   : '%phtml%/tracking/'
    itemTrack  : '%phtml%/wa_item_track/'
    waCotForm  : '%phtml%/wa_cot_form/'
    coolers    : '%phtml%/wa_coolers/'
    waSendmy   : '%phtml%/wa_sendmy/'
    waDemoCot  : '%phtml%/wa_demo_cot/'
    waRemOk    : '%phtml%/wa_rem_ok/'
    dtaCtc     : '%phtml%/ctcs/'
    dtaCtcLog  : '%dtaCtc%/log'
    anyMlm     : '%scm%/any_mlm.json'
    report     : '%scm%/report.txt'
    dictionary : '%scm%/dicc.json'
    
    ngile      : '%scm%ng_file.json'
    cnxFile    : '%scm%cnx_file.json'
    verapps    : '%scm%versions.json'
    tkwaconm   : '%scm%tkwaconm.json'

    getWaToken : '%env(resolve:WA_TOKEN)%'
    sufixUri   : '%env(resolve:SUFIX_URI)%'
    getAnToken : '%env(resolve:ANET_TOKEN)%'
    getShopCTk : '%env(resolve:SHOP_TOKEN)%'
    anetCnx    : '%env(resolve:ANET_CNX)%'

    # Revisar... posiblemente borrar
    reqRadec   : '%phtml%/req_radec/'
    waTemplates: '%phtml%/wa_templates/'
    waAnalizar : '%phtml%/wa_analizar/'
    sseNotRouteActive: '%phtml%/sse_not_route/'
    sseMetas   : '%phtml%/sse_metas/'
    sseFails   : '%phtml%/sse_fails/'
    comments   : '%phtml%/comments/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

