parameters:
    phtml      : '%kernel.project_dir%/public_html'
    datafix    : '%phtml%/datafix/'
    rutas      : '%datafix%/rutas.json'
    centiSchema: '%phtml%/cent_schema/centi_schema.json'
    scm        : '%phtml%/scm/'
    imgOrdTmp  : '%phtml%/to_orden_tmp/'
    imgOrd     : '%phtml%/to_orden/__idOrd__/__idPza__/'
    shareimgDev: '%phtml%/share_img_from_device/'
    imgOrdRsp  : '%phtml%/to_orden_rsp/'
    nifiFld    : '%phtml%/nifi/'
    ordAsigns  : '%phtml%/ordenes_asigns/'
    centinela  : '%phtml%/centinela.json'
    harbiConnx : '%phtml%/harbi_connx.json'
    filtros    : '%phtml%/filtros/'
    filtrosF   : '%filtros%/filtros.json'
    filNoTgo   : '%phtml%/filnotgo.json'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

