parameters:
    phtml      : '%kernel.project_dir%/public_html'
    datafix    : '%phtml%/datafix/'
    centinela  : '%phtml%/centinela.json'
    scm        : '%datafix%/scm.json'
    scmMsgsDef : '%datafix%/scm_mensajes.json'
    scmMsgs    : '%datafix%/scm_msgs/'
    harbiConnx : '%phtml%/harbi_connx.json'
    imgOrdTmp  : '%phtml%/to_orden_tmp/'
    imgOrd     : '%phtml%/to_orden/__idOrd__/__idPza__/'
    shareimgDev: '%phtml%/share_img_from_device/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
